### ISSUE TITLE
好像不让复制项目啊。

### ISSUE THREAD

**Issue by rocke** [jeffzh3ng/InsectsAwake#4]
正克隆到 'InsectsAwake'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights

**Comment by jeffzh3ng** [comment]
你使用Clone with HTTPS 试试，即： git clone https://github.com/jeffzh3ng/InsectsAwake.git

**Comment by rocke** [comment]
@jeffzh3ng 我使用的 UB 麒麟，请问下您用的是什么版本

**Comment by jeffzh3ng** [comment]
我使用的是Ubuntu 16.04

**Comment by rocke** [comment]
root@toor-virtual-machine:/home/toor/InsectsAwake# sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
Executing: /tmp/tmp.EmLctTbOVb/gpg.1.sh --keyserver
hkp://keyserver.ubuntu.com:80
--recv
2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
gpg: 下载密钥‘91FA4AD5’，从 hkp 服务器 keyserver.ubuntu.com
gpg: 密钥 91FA4AD5：“MongoDB 3.6 Release Signing Key <packaging@mongodb.com>”未改变
gpg: 合计被处理的数量：1
gpg:              未改变：1
